import Head from "next/head";
import Charts from "../components/Charts";
import DateTimePicker from "../components/DateTimePicker";
import CircleProgressBar from "../components/CircleProgressBar";
import Comment from "../components/Comment";
import AudioRecorder from "../components/AudioRecorder";

export default function Home() {
  const percentage = 89;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4 flex items-center justify-center">
        <div className="max-w-xl mx-auto">
          {/* <Charts /> */}
          {/* <CircleProgressBar percentage={percentage} /> */}
          <DateTimePicker percentage={percentage} />
          {/* <Comment /> */}
          {/* <AudioRecorder /> */}
        </div>
      </div>
    </>
  );
}
